version: '2'
services:

  # Service
  filesapp_server_dev:
    extends:
      file: ./filesapp_base.yml
      service: filesapp_server_base
    container_name: filesapp_server
    build:
      context: ./server
    command: bash -c "php /app/artisan migrate && apache2-wrapper"
    depends_on:
      - filesapp_db_dev
    networks:
      - filesapp_internal
    ports:
      - "5000:80"
    volumes:
      - ./server:/app
    environment:
      APP_URL: http://localhost:5000
      DB_HOST: filesapp_db_dev

  # Service
  filesapp_db_dev:
    extends:
      file: ./filesapp_base.yml
      service: mysql_base
    container_name: filesapp_db
    volumes:
          - "./server/.data/db_dev:/var/lib/mysql"
    networks:
      - filesapp_internal
    ports:
      - "3350:3306"


networks:
  filesapp_internal:
    driver: "bridge"
